### ISSUE TITLE
Unexpected token on compiling project

### ISSUE THREAD

**Issue by Sniffing** [sercand/cocos-creator-docker#1]
Hi, firstly, thank you for working on this. I'm involved in making mobil games with cocos creator too,

I've got a very basic docker container which just pulls from sercand/cocos-creator:1.9.0-web
Inside the container in interactive mode, I run a simple

`/opt/cocos-build.sh —path  . --build "platform=web-mobile`

Though face the following errors

`Error: Build Failed: Compile error: Unexpected token

/opt/cocos-creator/resources/app.asar/node_modules/events/events.js:1
^�~2�FΙ�*������xZ��L��C�tzx�cA���Z�z� c?�["쩔x�s9�k6+�(AI?����9�Nbh7)�N��Xj>t�Uvd�
^
ParseError: Unexpected token
    at Readable.<anonymous> (/opt/cocos-creator/resources/app.asar/editor/page/compile-worker.js:1:1514)
    at emitOne (events.js:96:13)
    at Readable.emit (events.js:191:7)
    at Labeled.<anonymous> (/opt/cocos-creator/resources/app.asar/node_modules/read-only-stream/index.js:28:44)
    at emitOne (events.js:96:13)
    at Labeled.emit (events.js:191:7)
    at Labeled.<anonymous> (/opt/cocos-creator/resources/app.asar/node_modules/stream-splicer/index.js:130:18)
    at emitOne (events.js:101:20)
    at Labeled.emit (events.js:191:7)
    at DestroyableTransform.<anonymous> (/opt/cocos-creator/resources/app.asar/node_modules/stream-splicer/index.js:130:18)
    at Async.series.t (/opt/cocos-creator/resources/app.asar/editor/core/builder.js:1:3024)
    at /opt/cocos-creator/resources/app.asar/node_modules/async/lib/async.js:726:13
    at /opt/cocos-creator/resources/app.asar/node_modules/async/lib/async.js:52:16
    at /opt/cocos-creator/resources/app.asar/node_modules/async/lib/async.js:264:21
    at /opt/cocos-creator/resources/app.asar/node_modules/async/lib/async.js:44:16
    at /opt/cocos-creator/resources/app.asar/node_modules/async/lib/async.js:723:17
    at /opt/cocos-creator/resources/app.asar/node_modules/async/lib/async.js:167:37
    at Gulp.doneCallback (/opt/cocos-creator/resources/app.asar/editor/core/gulp-build.js:1:18343)
    at Gulp.Orchestrator.stop (/opt/cocos-creator/resources/app.asar/node_modules/orchestrator/index.js:150:9)`

Any insight onto this?

**Comment by sercand** [comment]
@Sniffing In which step did you get the error

**Comment by Sniffing** [comment]
Ah sorry, the error happens at stage

```[558] assets-importer loaded  
[558] i18n loaded  
[558] Watching packages  
[558] Run Application  
init QuickCompiler: 965.293ms  
// Options object  
Start to build platform [web-mobile]
[558] Building /game
[558] Destination /game/build/web-mobile
[558] Delete /game/build/web-mobile/**/*
[  compile [] 10% 0.0s  ][558] Compiled project javascript file successfully
[558] Error: Build Failed: Compile error: Unexpected token```

**Comment by sercand** [comment]
@Sniffing another question. Can you build the game at your local machine with command line as described in [here](http://cocos2d-x.org/docs/creator/manual/en/publish/publish-in-command-line.html) . Most of the time CI build issue repeats itself on my local machine.

**Comment by Sniffing** [comment]
Yes, that has been building just fine locally

**Comment by vranac** [comment]
I have the same problem on all images from docker hub.
Could you share the process of building this image, so we could do it locally?
